spring.application.name=catalog-service
server.port=8088

# Activer refresh auto par actuator
management.endpoints.web.exposure.include=refresh

# Datasource — driver fixe
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Fallback local: garantit la creation du schema H2 meme si le Config Server est absent
spring.jpa.hibernate.ddl-auto=update

# H2 Console — chemin fixe
spring.h2.console.path=/h2
spring.h2.console.enabled=true

# Config Server
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888
welcome.message=Bienvenue sur le service de catalogue
