server.port=8888
spring.application.name=config-server

# Active le mode sans Git (fichiers locaux)
spring.profiles.active=native

# Dit au serveur de chercher les fichiers directement dans son dossier ressources
spring.cloud.config.server.native.search-locations=classpath:/config/spring.cloud.config.enabled=false
