spring.cloud.config.enabled=false
spring.config.import-check.enabled=false

# Configuration Generale de l'Application
spring.application.name=delivery-service
server.port=8084

# Config H2 Database pour development
spring.datasource.url=jdbc:h2:mem:deliverydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Actuator
management.endpoints.web.exposure.include=*
spring.config.import-check.enabled=false
