# Configuration Générale de l'Application
spring.application.name=delivery-service
server.port=8081

# Désactive la recherche obligatoire du Config Server Cloud (Résout l'erreur de démarrage)
spring.cloud.config.enabled=false

# Configuration de la Base de Données MySQL
# Utilisation du port 3307 comme spécifié dans ta configuration
spring.datasource.url=jdbc:mysql://localhost:3307/QuickDrop?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
# Force l'utilisation du dialecte MySQL approprié
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuration d'Eureka Client
# Activé à "true" pour que ton microservice s'enregistre bien sur le serveur de ton équipe
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


# Étape 1 : Demande à ton Spring Boot d'ouvrir les portes d'Actuator sur le Web
management.endpoints.web.exposure.include=*

# Étape 2 : Active explicitement l'endpoint /actuator/info
management.endpoint.info.enabled=true

# Étape 3 : Déclare les informations textuelles que ton service va afficher
info.app.name=QuickDrop Delivery Service
info.app.description=Microservice de gestion et orchestration des livraisons
info.app.version=1.0.0