# Base de données
spring.datasource.url=jdbc:h2:file:/app/Database/Data/Catalog;AUTO_SERVER=FALSE
spring.datasource.username=hayet
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=update

# Eureka
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
eureka.client.register-with-eureka=true

welcome.message= Welcome to Catalog MS from config server v2