server.port=8081

# Configuration MySQL
spring.datasource.url=jdbc:mysql://mysql:3306/QuickDrop?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuration Eureka Client
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Configuration Actuator Minimal
management.endpoints.web.exposure.include=*

# Indique a Spring Security ou recuperer les cles publiques pour valider le Token JWT
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/JobBoardKeycloack/protocol/openid-connect/certs
